<!DOCTYPE html>
<html>
<head>
    <title>Quiz Attempts Report</title>
    <style>
        @page {
            margin: 2.5cm;
            counter-increment: page;
            @bottom-right {
                content: "Page " counter(page) " of " counter(pages);
                font-family: 'Times New Roman', Times, serif;
                font-size: 12px;
            }
            @bottom-left {
                content: "Generated by: {{ $user->name }}";
                font-family: 'Times New Roman', Times, serif;
                font-size: 12px;
            }
        }

        body {
            font-family: 'Times New Roman', Times, serif;
            font-size: 14px;
            line-height: 1.4;
            color: #333333;
            margin: 0;
            padding: 0;
        }

        /* Cover page styling */
        .cover-page {
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-align: center;
            /*page-break-after: always;*/
        }

        .cover-logo {
            max-width: 300px;
            margin-bottom: 50px;
        }

        .cover-title {
            color: #002D62;
            font-size: 32px;
            margin: 30px 0;
            font-weight: bold;
        }

        .cover-meta {
            color: #555555;
            font-size: 16px;
            margin: 10px 0;
        }

        .confidential-notice {
            margin-top: 50px;
            color: #8B0000;
            font-size: 14px;
            font-weight: bold;
            text-transform: uppercase;
        }

        /* Content styling */
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #002D62;
            padding-bottom: 20px;
        }

        .logo {
            max-width: 180px;
            margin-bottom: 15px;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

        .attempt {
            page-break-before: always;
            margin-bottom: 25px;
            border-bottom: 1px solid #E5E5E5;
            padding-bottom: 20px;
        }

        .question {
            margin: 12px 0;
            padding: 15px 20px;
            page-break-inside: avoid;
            background-color: #F9F9F9;
            border-left: 3px solid #002D62;
        }

        .correct {
            color: #006400;
            font-weight: 500;
        }

        .incorrect {
            color: #8B0000;
            font-weight: 500;
        }

        .score {
            font-weight: bold;
            font-size: 16px;
            color: #002D62;
            margin: 15px 0;
        }

        .meta {
            color: #555555;
            font-size: 13px;
            margin: 8px 0;
        }

        h1 {
            color: #002D62;
            font-size: 24px;
            margin: 15px 0;
            font-weight: bold;
        }

        h3, h4 {
            color: #002D62;
            margin: 12px 0;
            page-break-after: avoid;
        }

        h3 {
            font-size: 18px;
        }

        h4 {
            font-size: 16px;
        }

        p {
            margin: 8px 0;
        }

        /* Prevent orphaned headers */
        h1, h2, h3, h4, h5 {
            page-break-after: avoid;
        }

        /* Prevent orphaned list items */
        li {
            page-break-inside: avoid;
        }

        .doc-info {
            margin-top: 30px;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <!-- Cover Page -->
    <div class="cover-page">
        <img src="imgs/natsave.png" alt="NatSave Logo" class="cover-logo">
        <h1 class="cover-title">Quiz Attempts Report</h1>
        <p class="cover-meta">User: {{ $user->name }}</p>
        <p class="cover-meta">Generated: {{ $generated_at }}</p>
        <p class="cover-meta">Document Reference: QAR-{{ date('Ymd') }}-{{ $user->id }}</p>
        <p class="doc-info">Version: 1.0</p>
        <p class="doc-info">Department: E-Learning</p>
        <p class="confidential-notice">Confidential Document</p>
    </div>

    <!-- Report Content -->
    @foreach($attempts as $attempt)
        @php
            $module = \App\Models\Module::find($attempt->module_id);
            $lesson = \App\Models\Lesson::find($attempt->lesson_id);
            $answers = \App\Models\AttemptAnswer::where('attempt_group_id', $attempt->attempt_group_id)->get();
            $total = $answers->count();
            $correct = $answers->where('auto_mark', 1)->count();
            $percentage = $total > 0 ? round(($correct / $total) * 100, 2) : 0;
        @endphp

        <div class="attempt">
            <div class="header">
                <img src="imgs/natsave.png" alt="NatSave Logo" class="logo">
            </div>

            <h3>Module: {{ $module->title ?? 'Unknown Module' }}</h3>
            <h4>Lesson: {{ $lesson->title ?? 'Unknown Lesson' }}</h4>
            <p class="meta">Attempted on: {{ $attempt->created_at->format('F d, Y H:i:s') }}</p>
            <p class="score">Score: {{ $correct }}/{{ $total }} ({{ $percentage }}%)</p>

            @foreach($answers as $answer)
                @php
                    $quiz = \App\Models\Quizz::find($answer->quiz_id);
                @endphp
                @if($quiz)
                    <div class="question">
                        <p><strong>Q:</strong> {{ $quiz->question }}</p>
                        <p class="{{ $answer->auto_mark ? 'correct' : 'incorrect' }}">
                            Your Answer: {{ $answer->user_answer }}
                            @if(!$answer->auto_mark)
                                (Correct: {{ $quiz->correct_answer }})
                            @endif
                        </p>
                    </div>
                @endif
            @endforeach
        </div>
    @endforeach
</body>
</html>
